version: "3.9"

services:
  v380:
    image: ghcr.io/romaxa55/romaxa55/v380_cams_hack/v380:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: v380_cams
    environment:
      # Переменные окружения в контейнере.
      # Значения, начинающиеся с "$", будут взяты из вашего локального окружения
      # или из файла .env, если он находится в той же директории, что и docker-compose.yml
      # Однако прямо указанные значения (как START_ID, END_ID и BATCH_SIZE ниже)
      # будут переданы в контейнер "как есть".

      START_ID: 19348439  # Статическое значение, передаваемое в контейнер напрямую.
      END_ID: 29748452  # Статическое значение.
      BATCH_SIZE: 100  # Статическое значение.
      TELEGRAM_TOKEN: $TELEGRAM_TOKEN  # Значение из вашего окружения или файла .env.
      TELEGRAM_CHAT_ID: $TELEGRAM_CHAT_ID  # Аналогично.
    restart: always
